# Generated by Django 5.1 on 2024-08-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_studentnew_internshipdomain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("feedback", models.TextField()),
            ],
        ),
    ]
